### ISSUE TITLE
Executable fails if project was never opened in Godot

### ISSUE THREAD

**Issue by ChrisJAllan** [silphendio/vr-media-player#4]
Steps taken:
1. Install prerequisites
2. clone git
3. ./build.sh
4. ./Godot_v3.5.1-stable_x11.64

Crash log:
[log.txt](https://github.com/silphendio/vr-media-player/files/11362617/log.txt)

After opening the project in Godot and re-running build.sh, the executable runs without crashing.

**Comment by silphendio** [comment]
I don't use that build script anymore.
